spring.application.name=NauJava
app.name=Sheet Music Library
app.version=1.0.0

management.endpoints.web.exposure.include=*

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update